# Uncomment the next line to define a global platform for your project
platform :ios, '13.6'

target 'virtualTours' do
  use_frameworks!

  # Pods for VirtualTours
  pod 'GoogleMaps'
  pod 'ARCL'
  pod 'GooglePlaces', '4.2.0'
  pod 'GooglePlaces'
end
