# Uncomment the next line to define a global platform for your project
# platform :ios, '14.3'

target 'virtualTours' do
  use_frameworks!

  # Pods for VirtualTours
  pod 'GoogleMaps', '4.2.0'
  pod 'GooglePlaces', '4.2.0'

end
